#!/bin/bash

function start_conky {
    conky -q -c ~/.config/conky/conky-screensaver-"$1".conf &
    PIDS+=($!)
}

function kill_conky {
    for PID in ${PIDS[@]}; do
        kill -9 $PID
    done
}

# conky pids
PIDS=()

# conky for monitor
start_conky "DP-1"

# conky for laptop screen
start_conky "eDP-1"

# lock
swaylock -u -c 00000000

# kill conky
kill_conky
