#!/bin/bash
# shutdown options for i3

case "$1" in
    lock)
        /home/rama/.config/i3/lockscreen
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        /home/rama/.config/i3/lockscreen && systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    poweroff)
        systemctl poweroff
        ;;
esac
