#!/bin/bash

# exit if already locked
if pgrep -x i3lock > /dev/null
then
    exit
fi

# disable notifications
killall -SIGUSR1 dunst

# turn off screen if i3lock is still running
(sleep 60; pgrep -x i3lock && xset dpms force off) &

# lock, don't fork
i3lock -i $HOME/Pictures/lockscreen.png -o '#ffffff' -w 'aa0000' -l '#ffffff' -e -n

# reenable notifications
killall -SIGUSR2 dunst
