#!/bin/bash

function log {
    echo "$1" >> $HOME/.config/dunst/log
}

log "$(date)"
log "sending message"
ERROR="$(messer --command='message "Neehath Malisetty" 😡' 2>&1)"
if [[ $? = 0 ]]
then
    log "message sent"
else
    log "message failure $? ($ERROR)"
fi

rm api.debug.log messen.debug.log > /dev/null 2>&1
log "exiting"
